### ISSUE TITLE
Toggle is set but do not send value after selecting scene

### ISSUE THREAD

**Issue by sahver** [m---w/kollabs#4]
Hey,

It seems that if a toggle's send/receive parameters are identical then value is only set but not sent. With regular number box the inlet and outlet dissapears if send/receive are set. With Number2 the inlet and outlet are available but behaviour is same as with toggle.

Therefore the presets can be loaded but the values are not triggered.

I am using PD 0.47.1. [Test patch](https://github.com/m---w/kollabs/files/1118976/test-kollabs.zip) attached.

**Comment by m---w** [comment]
This behavior of toggles and numberboxes with send/receive is totally normal. The usual approach is to separate GUI and logic: The logic of the patch listens to a variable via [receive /variablename]. The variable is set via a GUI with both send/receive set to "/variablename". Kollabs also listens to this address and updates it if a preset is loaded.
