### ISSUE TITLE
Recall of table with large numbers doesn't work

### ISSUE THREAD

**Issue by dsp1986** [m---w/kollabs#5]
I have difficulty understanding the following:
## SETUP:
I have a list of frequency values that I store in a table by sending the list to it.
I registered the table in the right domain. It works fine with values in the default range -1:1.
## PROBLEM:
when I store a set of large numbers (frequency values in the range 30:2000) the values don't get restored anymore. When I save to the textfile I can see that storing works. Just the recall doesn't.

**Comment by m---w** [comment]
Works fine for me. Perhaps you just didn't set the ranges of your table properly (usually -1 to 1, set them with rightclick-->properties on the table object). This means, the table just _looked_ empty, because all values were larger than 1.
